SUBJECTS = [
    "Urgent: Account Compromised",
    "Security Alert: Unauthorized Access Detected",
    "Important: Immediate Account Recovery Required",
    "Action Needed: Account Breach Detected",
    "Emergency: Account Locked Due to Suspicious Activity",
    "Critical: Unauthorized Login on Your Account",
    "Notice: Account May Be at Risk",
    "Immediate Assistance Needed: Account Hijacked",
    "Alert: Possible Phishing Incident",
    "Security Notification: Strange Login Attempts",
    "Warning: Account Access From Unknown Device",
    "Urgent Review: Account Security Issue",
    "Immediate Response Required: Account Misuse",
    "Important: Unusual Activity Noticed",
    "Security Alert: Account Access Warning",
    "Emergency: Unauthorized Use Detected",
    "Account Support: Help Request for Hacked Account",
    "Security Warning: Account Taken Over",
    "Urgent Support Request: Locked Out of Account",
    "Account Recovery Assistance Needed",
    "Critical Notice: Account Credentials Exposed",
    "Help Needed: Compromised Login Detected",
    "Immediate Security Help Required",
    "Alert: Account Access Breach",
    "Security Report: Account Under Threat",
    "Notice: Suspicious Device Logged In",
    "Action Needed: Prevent Unauthorized Access",
    "Urgent: Lost Control of My Account",
    "Security Breach: Help Regain Access",
    "Important: Someone Else Accessed My Account",
    "Assistance Request: Account Restored",
    "Emergency: Password Reset Failed",
    "Critical Help: Account Hacked",
    "Alert: Unknown Email Linked to My Account",
    "Warning: Account Integrity at Risk",
    "Immediate Lockdown Request",
    "Help: My Account Was Stolen",
    "Security Assistance Request",
    "Important: Verify Account Ownership",
    "Emergency: Account Suspended by Mistake"
]


BODIES = [
    lambda id, phone: f"Hello, my account (ID: {id}, phone: {phone}) seems to be compromised. Please help me secure it immediately.",
    lambda id, phone: f"I lost access to my account (ID: {id}). It was likely phished. Kindly block all sessions and assist in recovery. My phone number is {phone}.",
    lambda id, phone: f"My profile (ID: {id}, phone: {phone}) was hacked today. Please restrict any login attempts and help me regain full control.",
    lambda id, phone: f"Suspicious activity detected on my account (ID: {id}, phone: {phone}). Please freeze all access and restore my ownership as soon as possible.",
    lambda id, phone: f"I urgently need help recovering my compromised account (ID: {id}, phone: {phone}). Please terminate all active sessions and secure it immediately.",
    lambda id, phone: f"I noticed multiple unauthorized logins on my account (ID: {id}, phone: {phone}). Please review the access logs and revoke suspicious sessions.",
    lambda id, phone: f"My account (ID: {id}, phone: {phone}) has shown strange login activity from locations I don’t recognize. Kindly investigate and secure it.",
    lambda id, phone: f"I believe my account (ID: {id}, phone: {phone}) has been hijacked. I cannot log in anymore. Please restore access and reset credentials.",
    lambda id, phone: f"I may have clicked a phishing link, and now my account (ID: {id}, phone: {phone}) behaves oddly. Please help me recover it safely.",
    lambda id, phone: f"I received alerts about unusual sign-ins on my account (ID: {id}, phone: {phone}). Please verify and lock unauthorized devices.",
    lambda id, phone: f"I think someone else is using my account (ID: {id}, phone: {phone}). I noticed actions I didn’t perform. Please help secure it.",
    lambda id, phone: f"There’s been an unauthorized attempt to change my password on account (ID: {id}, phone: {phone}). Please stop any pending changes immediately.",
    lambda id, phone: f"My account (ID: {id}, phone: {phone}) has been locked due to suspicious activity. Please guide me through recovery steps.",
    lambda id, phone: f"I suspect a data breach on my account (ID: {id}, phone: {phone}). Please investigate and ensure my personal information is safe.",
    lambda id, phone: f"Hi, I’m reaching out because I noticed activity I don’t recognize on my account (ID: {id}, phone: {phone}). Please assist urgently.",
    lambda id, phone: f"I think my account (ID: {id}, phone: {phone}) was accessed by someone else. Please reset the password and verify my identity.",
    lambda id, phone: f"My account (ID: {id}, phone: {phone}) was recently compromised. Please disable all unauthorized logins and help restore my access.",
    lambda id, phone: f"Unauthorized access was detected on my profile (ID: {id}, phone: {phone}). Please lock the account and prevent further misuse.",
    lambda id, phone: f"I’m locked out of my account (ID: {id}, phone: {phone}) after receiving security warnings. Please help me regain control safely.",
    lambda id, phone: f"My credentials for account (ID: {id}, phone: {phone}) may have leaked. Please reset the password and verify ownership.",
    lambda id, phone: f"I need urgent help with my account (ID: {id}, phone: {phone}). It was hacked today and someone changed key details. Please assist.",
    lambda id, phone: f"I noticed a login from an unknown country on my account (ID: {id}, phone: {phone}). Please investigate and secure it.",
    lambda id, phone: f"Please help, I suspect my account (ID: {id}, phone: {phone}) was compromised by malware. Kindly check and restore its integrity.",
    lambda id, phone: f"I’m reporting a breach on my account (ID: {id}, phone: {phone}). Please review access logs and revoke unknown devices.",
    lambda id, phone: f"Someone might be trying to steal my account (ID: {id}, phone: {phone}). Please verify ownership and secure my data.",
    lambda id, phone: f"I cannot access my account (ID: {id}, phone: {phone}) after someone changed the recovery information. Please restore it.",
    lambda id, phone: f"My account (ID: {id}, phone: {phone}) shows signs of tampering. Please perform a full security audit and reset credentials.",
    lambda id, phone: f"I’ve lost full access to my account (ID: {id}, phone: {phone}) due to a suspected hack. Please block all devices immediately.",
    lambda id, phone: f"I noticed someone else using my account (ID: {id}, phone: {phone}). Please terminate sessions and reset access settings.",
    lambda id, phone: f"My account (ID: {id}, phone: {phone}) might be under attack. Please freeze all actions and verify my control over it.",
    lambda id, phone: f"I’m requesting help to restore my account (ID: {id}, phone: {phone}) which was compromised earlier today.",
    lambda id, phone: f"My password reset failed several times for account (ID: {id}, phone: {phone}). It may be hijacked. Please investigate.",
    lambda id, phone: f"I’ve been notified that my account (ID: {id}, phone: {phone}) was accessed from a strange email address. Please unlink it.",
    lambda id, phone: f"My account (ID: {id}, phone: {phone}) may have been used for unauthorized actions. Please verify and fix immediately.",
    lambda id, phone: f"I request an immediate lockdown of my account (ID: {id}, phone: {phone}) as I suspect it’s being accessed remotely.",
    lambda id, phone: f"I think someone stole my account (ID: {id}, phone: {phone}). Please recover ownership and change all credentials.",
    lambda id, phone: f"I’m requesting urgent security assistance for account (ID: {id}, phone: {phone}) — it shows unknown login attempts.",
    lambda id, phone: f"Please verify ownership of my account (ID: {id}, phone: {phone}). I believe someone else gained control.",
    lambda id, phone: f"My account (ID: {id}, phone: {phone}) was suspended by mistake after a false alert. Please reactivate it securely.",
    lambda id, phone: f"I received multiple failed login attempts on my account (ID: {id}, phone: {phone}). Please review and secure all access points."
]

def make_report_text(target_id, target_phone):
    import random
    subject = random.choice(SUBJECTS)
    body = random.choice(BODIES)(target_id, target_phone)
    return f"{subject}\n\n{body}"